server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;
  default_type application/octet-stream;

  types {
    text/html html htm shtml;
    text/css css;
    application/javascript js mjs;
    application/json json map;
    image/svg+xml svg svgz;
    application/wasm wasm;
    application/pdf pdf;
    image/avif avif;
    image/webp webp;
    image/png png;
    image/jpeg jpeg jpg;
    image/gif gif;
    font/woff woff;
    font/woff2 woff2;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /assets/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}
